### ISSUE TITLE
pvp is completely disabled

### ISSUE THREAD

**Issue by Mrs-Feathers** [jrbudda/Vivecraft_115#12]
loading the plugin at all disables all pvp, regardless of if its set to true or false for any or all 3 of the pvp values. even vanilla vs vanilla players are affected.

**Comment by jrbudda** [comment]
Well thats bad. Are there errors in the console window?

**Comment by Mrs-Feathers** [comment]
none that i can see. also, this is tested without any other plugins in as well and same issue. im running ubuntu server edition. spigot 1.15.2

**Comment by Mrs-Feathers** [comment]
noting further on errors: start up is normal. enables without issue.

**Comment by jrbudda** [comment]
If there's no errors I can't see how we could be interfering with PVP at all... This is the first report of this issue. What version of the plugin are you running? The plugin updated recently but the PVP settings code has not changed.

**Comment by Mrs-Feathers** [comment]
84e95bc

**Comment by jrbudda** [comment]
That's a link to the client. You were stating a problem with the spigot extensions plugin, which is not this repository.

**Comment by Mrs-Feathers** [comment]
i'm sorry, i was confused because there's only litterally one version working for spigot 1.15.2 which is "d59294e" on this repository: https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases

being that there is only one version i thought you meant client because there are multiple versions of that... which is also a question i would ask "what client are you getting this issue with?"

is there currently a way to just turn pvp handling off and just handle it as vanilla?

**Comment by jrbudda** [comment]
There's been 6 releases of the spigot plugin for 1.15. r1 to r6. are you running r6 on your server?

**Comment by Mrs-Feathers** [comment]
no it seems like r4. i will install the latest version r6 and check back

**Comment by Mrs-Feathers** [comment]
awesome! it seems to work perfect now! thanks for the update! seems like the issue was only for that earlier version.
