### ISSUE TITLE
Audio not working.

### ISSUE THREAD

**Issue by TMMarkus** [jrbudda/Vivecraft_115#24]
Hello, i have an issue with audio, literally i can't hear any sound of the game, i checked the audio configuration in Windows 10 and tried to reinstall the version, but nothing fix it. Any solution?

**Comment by Espergium** [comment]
Minecraft uses the primary audio device at time of launch. Make sure SteamVR is also making use of the intended devices.

**Comment by TMMarkus** [comment]
Only happen when i use the version 1.15.2, but when i'm used 1.12.2 or others, works fine.

**Comment by TMMarkus** [comment]
Okay, i fixed it installing first the version 1.15.2 vanilla in the launcher and then installing the vivecraft version.
