### ISSUE TITLE
NonVR Game wont launch on linux

### ISSUE THREAD

**Issue by Da-Boom** [jrbudda/Vivecraft_115#4]
The game will install via `java -jar vivecraft-1.15.2-jrbudda-NONVR-2-r1-installer.exe`

But when i use the launcher to launch it, the game crashes - it does not leave any logs
(the log window just says `waiting for log output`) and running the launcher in the terminal gives me this error, which may or may not have anything to do with the mod:

`[0421/153748.648712:WARNING:x11_util.cc(1349)] X error received: serial 815, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)`

I'm running Manjaro with kernel 5.6.5-3-MANJARO and I've tried various different java versions, including the minecraft built in java, java-10-openjdk, java13-openjdk and java-8-openjdk, it all ends with the exact same result.

I do not know if this works with the VR version as I do not own a VR headset

**Comment by Techjar** [comment]
Does vanilla minecraft work?

**Comment by Da-Boom** [comment]
Yes, and so does minecraft with optifine

**Comment by Nathan22211** [comment]
I think the main problom here is that it's trying to run as if it's a windows machine through WINE since it emulates the installation being in a C: drive. the solution would be a .deb package or a universal jar to install the mod

**Comment by Techjar** [comment]
No, the installer is just a Java application. When you run it with `java -jar` it's running natively on Linux, and we use the same function to get the .minecraft directory as Minecraft itself. Attempt to launch the game again, then upload `launcher_log.txt` from the .minecraft directory for us to take a look at.

**Comment by Da-Boom** [comment]
Ok, so idk what changed with NONVR-2-r2, but the problem appears to be fixed. Its launching just fine.
