### ISSUE TITLE
Need .jar file to add Vivecraft to a modpack

### ISSUE THREAD

**Issue by Cryothemium** [jrbudda/Vivecraft_115#9]
Hi, I am building a modpack for me and my friends using Twitch's custom modpack feature. I need a .jar file for each mod, but I am unable to find .jar file for Vivcraft, or at least one that is recognized as a mod. Any help would be appreciated. I am running Windows 10, I am creating a 1.15.2 server, and I use Serverminer as my server host. I have used Serverminer with Vivecraft previously, although in vanilla 1.15.2.

Thanks.

**Comment by Cryothemium** [comment]
I have found a file named vivecraft-1.15.2-jrbudda-2-r2.jar under roaming, but it says it is not a valid mod file.

**Comment by Espergium** [comment]
Vivecraft is not a mod. It needs installed over top of a profile.

**Comment by Cryothemium** [comment]
Thank you, I did not know that! I will try that now.

**Comment by Cryothemium** [comment]
It seems that I am unable to find the profile that twitch uses when launching Minecraft, as it is not in the versions folder under .minecraft, and I am unable to install Vivecraft. Should I use an alternate method, or is there a way I can find the profile used by Twitch, so that I can install Vivecraft over it?

**Comment by jrbudda** [comment]
Using vivecraft with a modpack is covered in our FAQ on the website. Vivecraft 1.15 also does not currently support Forge mods. Only 1.12.

**Comment by Cryothemium** [comment]
Hello, and I apologize, I had not seen that. Thank you for your help. Is Forge support something that is currently planned to be implemented within the next 2 years?

**Comment by jrbudda** [comment]
more like next 2 weeks, have a working alpha now

**Comment by Cryothemium** [comment]
That's amazing! Thank you so much for your help, and I apologize for my ignorance concerning the FAQ page. (:
